services:
  - type: web
    name: flask-fire-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    envVars:
      - key: PORT
        value: 10000
